PRAGMA foreign_keys = OFF;

CREATE TABLE books_next (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL,
  title TEXT NOT NULL DEFAULT '',
  working_title TEXT NOT NULL DEFAULT '',
  premise TEXT NOT NULL DEFAULT '',
  protagonist_summary TEXT NOT NULL DEFAULT '',
  protagonist_goal TEXT NOT NULL DEFAULT '',
  expanded_premise TEXT NOT NULL DEFAULT '',
  logline TEXT NOT NULL DEFAULT '',
  central_conflict TEXT NOT NULL DEFAULT '',
  antagonist_force TEXT NOT NULL DEFAULT '',
  stakes TEXT NOT NULL DEFAULT '',
  setting_sketch TEXT NOT NULL DEFAULT '',
  ending_direction TEXT NOT NULL DEFAULT '',
  genre TEXT NOT NULL DEFAULT '',
  subgenre TEXT NOT NULL DEFAULT '',
  target_audience TEXT NOT NULL DEFAULT '',
  tone TEXT NOT NULL DEFAULT '',
  style_guide TEXT NOT NULL DEFAULT '',
  point_of_view TEXT NOT NULL DEFAULT '',
  target_word_count INTEGER,
  themes_json TEXT NOT NULL DEFAULT '[]',
  unwanted_themes TEXT NOT NULL DEFAULT '',
  alternative_titles_json TEXT NOT NULL DEFAULT '[]',
  cover_image_path TEXT NOT NULL DEFAULT '',
  cover_prompt TEXT NOT NULL DEFAULT '',
  cover_negative_prompt TEXT NOT NULL DEFAULT '',
  cover_generated_at TEXT,
  status TEXT NOT NULL DEFAULT 'draft',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

INSERT INTO books_next (
  id,
  project_id,
  title,
  working_title,
  premise,
  protagonist_summary,
  protagonist_goal,
  expanded_premise,
  logline,
  central_conflict,
  antagonist_force,
  stakes,
  setting_sketch,
  ending_direction,
  genre,
  subgenre,
  target_audience,
  tone,
  style_guide,
  point_of_view,
  target_word_count,
  themes_json,
  unwanted_themes,
  alternative_titles_json,
  cover_image_path,
  cover_prompt,
  cover_negative_prompt,
  cover_generated_at,
  status,
  created_at,
  updated_at
)
SELECT
  id,
  project_id,
  title,
  working_title,
  premise,
  '',
  '',
  expanded_premise,
  logline,
  central_conflict,
  '',
  stakes,
  '',
  '',
  genre,
  subgenre,
  target_audience,
  tone,
  style_guide,
  point_of_view,
  target_word_count,
  themes_json,
  unwanted_themes,
  alternative_titles_json,
  cover_image_path,
  cover_prompt,
  cover_negative_prompt,
  cover_generated_at,
  status,
  created_at,
  updated_at
FROM books;

DROP TABLE books;
ALTER TABLE books_next RENAME TO books;
CREATE INDEX idx_books_project_id ON books(project_id);

PRAGMA foreign_keys = ON;
