ALTER TABLE books ADD COLUMN expanded_premise TEXT NOT NULL DEFAULT '';
ALTER TABLE books ADD COLUMN central_conflict TEXT NOT NULL DEFAULT '';
ALTER TABLE books ADD COLUMN stakes TEXT NOT NULL DEFAULT '';
ALTER TABLE books ADD COLUMN themes_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE books ADD COLUMN unwanted_themes TEXT NOT NULL DEFAULT '';
ALTER TABLE books ADD COLUMN alternative_titles_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE books ADD COLUMN title_choice_note TEXT NOT NULL DEFAULT '';
